

CATEGORY_CHOICES = [
        ('', '----------'),
        ('tech', 'Tecnología'),
        ('fina', 'Finanzas'),
        ('salu', 'Salud'),
        ('educ', 'Educación'),
        ('ecom', 'Comercio Electrónico'),
        ('manu', 'Manufactura'),
        ('retl', 'Venta al por Menor'),
        ('tran', 'Transporte'),
        ('cons', 'Construcción'),
        ('cons', 'Consultoría'),
        ('real', 'Bienes Raíces'),
        ('phar', 'Farmacéutico'),
        ('auto', 'Automotriz'),
        ('ente', 'Entretenimiento'),
        ('medi', 'Medios'),
        ('tele', 'Telecomunicaciones'),
        ('legal', 'Legal'),
        ('hosp', 'Hospitalidad'),
        ('alib', 'Alimentación y Bebidas'),
        ('ener', 'Energía'),
        ('rene', 'Energías Renovables'),
        ('text', 'Textiles'),
        ('agri', 'Agricultura'),
        ('soft', 'Software'),
        ('hard', 'Hardware'),
        ('biot', 'Biotecnología'),
        ('fins', 'Servicios Financieros'),
        ('insu', 'Seguros'),
        ('gobi', 'Gobierno'),
        ('tour', 'Turismo'),
        ('nflp', 'Sin Fines de Lucro'),
        ('arts', 'Artes'),
        ('spor', 'Deportes'),
        ('game', 'Juegos'),
        ('inte', 'Internet'),
        ('logi', 'Logística'),
        ('ship', 'Transporte Marítimo'),
        ('aero', 'Aeroespacial'),
        ('defe', 'Defensa'),
        ('spac', 'Espacio'),
        ('medi', 'Medios y Entretenimiento'),
        ('chem', 'Químico'),
        ('dmed', 'Dispositivos Médicos'),
        ('plas', 'Plásticos'),
        ('cons', 'Consultoría'),
        ('recy', 'Reciclaje'),
        ('pers', 'Servicios Personales'),
        ('otro', 'Otro'),
    ]